### ISSUE TITLE
Could we extend this to IOS?

### ISSUE THREAD

**Issue by ravnarayan** [Aevi-UK/android-pos-print-api#49]
Can we extend this to IOS?

**Comment by brettwold** [comment]
Hi, this API (and all our newer AEVI APIs) are designed from the ground up to be compatible with other operating systems, such as iOS. It is entirely possible that we could/will create a iOS version (library) for this API in the fullness of time.

We would of course need a business and use case for this though. If you have one by all means get in touch.

**Comment by ravnarayan** [comment]
Hey Brettwold,

Thank you for letting me know, also sorry for the late reply. I would like to do exactly what this API is capable of doing. But I wanted to use IOS system over the android. Would this be something you and your team could do?

Thank you,

Rav
